### ISSUE TITLE
Issue: Controlls not working in Alleyway (GB)

### ISSUE THREAD

**Issue by ThreeM-MMM** [budude2/openfgpa-GBC#19]
When attempting to play Alleyway on the Gameboy Core, the D-Pad doesn't work. GBC core is also affected.

## Expected Behavior
D-Pad controls the Charakter

## Current Behavior
Character does not move. The paddle immediately moves to the left of the screen, as if D-Pad left is being held down (hence no other directions working).

## Possible Solution
When using the spiritualized core, the controls function as expected.

## Steps to Reproduce
1. Start Analogue Pocket
2. Select openFPGA and Gameboy
3. Change core to budude2 GB core
4. Select Alleyway rom
5. Push Start to start the game
6. Try to move the charakter

## Context (Environment)
AnalogueOS: v2.0
Core version: v1.0.3 (GB and GBC)
Rom CRC/Sha1: 5cc01586 (validated)

**Comment by SaulGoodman1337** [comment]
I can confirm that.

**Comment by nortakales** [comment]
The paddle immediately moves to the left of the screen, as if D-Pad Left is being held down (hence no other directions working). Hopefully that gives a clue to what is wrong.

**Comment by MP2E** [comment]
Just tested the latest MiSTer GameBoy Core this is ported from and the issue is not present there

**Comment by Dahak66** [comment]
Alleyway controls are working in 1.0.5.

**Comment by Dahak66** [comment]
Alleyway controls are working in release 1.0.5.

**Comment by MP2E** [comment]
Yep confirmed! It's working perfectly now

**Comment by ThreeM-MMM** [comment]
Confirmed. Working now. Thanks
