### ISSUE TITLE
Link cable support

### ISSUE THREAD

**Issue by Dahak66** [budude2/openfgpa-GBC#22]
Currently link cable doesn’t appear to be supported (I’ve only tried with two Analogue Pockets using an Analogue link cable) by the core. Attempted with Tetris on both devices, with cable switch set to GB/C. Works as expected in Spiritualized1997 core for same platform, using same technique (plugged in both devices, started core with same rom, select 2 player, press start.)

**Comment by budude2** [comment]
Correct, I tried to set it up but had to order a cable to debug it.

**Comment by budude2** [comment]
Added
