### ISSUE TITLE
Screen cuts witch analogue filters.

### ISSUE THREAD

**Issue by hgage2003** [budude2/openfgpa-GBC#26]
When I turn on Analogue GBC filters on GBC core, screen becomes cropped on the left. This issue is only on gbc core, gb core scales fine

**Comment by DunhamGitHub** [comment]
> When I turn on Analogue GBC filters on GBC core, screen becomes cropped on the left. This issue is only on gbc core, gb core scales fine

Is it too much to ask to add a screenshot / photo? Common sense, no?

**Comment by hgage2003** [comment]
![IMG_1331](https://github.com/budude2/openfgpa-GBC/assets/14826472/e81541d2-fd01-416e-aff5-ee82698c8ae7)
![IMG_1332](https://github.com/budude2/openfgpa-GBC/assets/14826472/593fa730-2da6-4bb9-a3a6-e528a2e16230)

**Comment by SaulGoodman1337** [comment]
I think your way of communicating and asking for help is really completely wrong. 


I certainly can't recreate it.
You should read through this documentation again and correct your video.json.
https://www.analogue.co/developer/docs/core-definition-files/video-json

**Comment by hgage2003** [comment]
I redownloaded the core from this github releases with video.json for testing and nothing changed. My video.json was the same, as in release 1.0.5. Also, I dont think the problem is in video.json - theese screen modes require core responce to work. The same video.json in gb core work perfect.

I think I opened an issue correctly and fully described it, I thought it is common overlooked bug. So I didn't though the screensots was nessesary. But when DunhamGitHub asked for it, I made photos. 
My English is not very good and I did not meen any offence.

**Comment by SaulGoodman1337** [comment]
please poste your video.json

**Comment by Dawbo66** [comment]
> When I turn on Analogue GBC filters on GBC core, screen becomes cropped on the left. This issue is only on gbc core, gb core scales fine

Try turning integer+ off , with that off I can go through the filters and they work as should.

**Comment by hgage2003** [comment]
> > When I turn on Analogue GBC filters on GBC core, screen becomes cropped on the left. This issue is only on gbc core, gb core scales fine
> 
> Try turning integer+ off , with that off I can go through the filters and they work as should.

Oh thank you! This was the issue!
Closed

**Comment by Dawbo66** [comment]
No worries.. 😁
