### ISSUE TITLE
Rhino Rumble causes the core to start as if a cartridge is inserted wrong.

### ISSUE THREAD

**Issue by IdiotBlueMage** [budude2/openfgpa-GBC#27]
Basically, select the file and you see a familiar game boy screen with a garbled nintendo logo.

Figured this might be of interest as this works on the original MiSTer core.  There may or may not be a couple other games like this.

**Comment by IdiotBlueMage** [comment]
An update on this.  Sgt. Rock is another game with this behavior.  When run in the spiritualized core, both games result in a red error message.

**Comment by hgage2003** [comment]
I think maybe you have bad dumps of theese games? All three games work fine on my pocket with this gbc core and Spiritualized core too.

**Comment by IdiotBlueMage** [comment]
Yeah I think you're right.  For some reason even though they worked on the original
