### ISSUE TITLE
Pocket Monsters : Crystal Version [Japan] savefile wrong.

### ISSUE THREAD

**Issue by Lingline** [budude2/openfgpa-GBC#28]
PM_CRYSTAL | 2048 | 64 | ROM+MBC3+RAM+Battery+Timer
save file 64k not 32k
32k is wrong
selecting girl save game,load game girl change boy
pls fix it

**Comment by Lycoris2013** [comment]
This is a peculiar problem with openfpga-GBC, as it works without problem with MiSTer fpga.
It seems to assume only 32 KB+RTC data size when writing.
Changing the data.json file to "size_maximum": "0x16050" will load 64KB of data.

**Comment by Lingline** [comment]
I changed the data.json file to "size_maximum": "0x16050" but save date alway 32k.

**Comment by Xukkorz** [comment]
The dev is aware of this issue, they didn't realize saves could be bigger than 32k and are working on correcting this.

**Comment by budude2** [comment]
Fixed in latest release (v1.0.7)
