### ISSUE TITLE
Stereo channels appear to be swapped in both the GB and GBC cores.

### ISSUE THREAD

**Issue by JayroJones** [budude2/openfgpa-GBC#39]
I have created a Gameboy Test Cartridge for the Gameboy Color. While testing the ROM on all of the different Analogue Pocket cores, I discovered that these two cores play the opposite audio channels than what is expected.

Core version used: v1.0.7
Cores affected: GB and GBC

Here's my test ROM so you can experiment and see for yourself:
[Stereo Tester.zip](https://github.com/budude2/openfgpa-GBC/files/14350415/Stereo.Tester.zip)

**Comment by hallmeier** [comment]
Oh yeah, they are! I tested using Flamethrower in Pokémon Crystal :D

I also found the cause, a mix-up in the code (#41). If you don't want to wait until budude releases a new version, I compiled packages including this fix [here](https://github.com/hallmeier/openfgpa-GBC/tree/master/pkg).
