### ISSUE TITLE
Error in framework Fileid 5 Filesize bad

### ISSUE THREAD

**Issue by Noble3781** [budude2/openfgpa-GBC#5]
Error in framework Fileid 5 Filesize bad

I select a game then it asks me to select a file after - I select GBC_ Bios

How do i fix this??

With the spirt core i just select the game and it boots right in to it, I have put in the bios files.

**Comment by basvroegop** [comment]
Do you also have gb_bios.bin in the same folder? Adding that seemed to fix it for me.

**Comment by insanedude63** [comment]
> Do you also have gb_bios.bin in the same folder? Adding that seemed to fix it for me.

This does indeed fix the issue

**Comment by Noble3781** [comment]
> Do you also have gb_bios.bin in the same folder? Adding that seemed to fix it for me.

That worked thank you :) !
