### ISSUE TITLE
desaturated colours 

### ISSUE THREAD

**Issue by Noble3781** [budude2/openfgpa-GBC#6]
Compared to other GBC Cores the colours are desaturated in the no filter mode.

**Comment by aggiemex** [comment]
> Compared to other GBC Cores the colours are desaturated in the no filter mode.

This also happens on the GB core. When using the Original DMG filter on this core the colors don't match the cartridge. 

See attached photo of the mushroom in Super Mario Land. It should have a dark top but using this core it looks white.

![DMG Differences](https://github.com/budude2/openfgpa-GBC/assets/104154861/dd5a1bc0-0510-4819-8585-0815605226a1)

**Comment by pyth27** [comment]
@aggiemex The game is running in GBC mode with the DMG filter applied. Looks fine to me in the GB core from the latest release (1.0.1).

**Comment by aggiemex** [comment]
@pyth27 Thank you! Updating to 1.0.1 and using the GB core resolved the issue!!!

**Comment by budude2** [comment]
Desaturated colors in GBC core should be fixed in 1.0.2
